# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Build
        run: make release-all-architectures

      - name: Test
        run: go test -v ./...

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qif-converter-linux-amd64
          path: ./target/qif-converter-linux-amd64

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qif-converter-linux-arm64
          path: ./target/qif-converter-linux-arm64

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qif-converter-darwin-amd64
          path: ./target/qif-converter-darwin-amd64

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qif-converter-darwin-arm64
          path: ./target/qif-converter-darwin-arm64

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qif-converter-windows-amd64
          path: ./target/qif-converter-windows-amd64

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qif-converter-windows-arm64
          path: ./target/qif-converter-windows-arm64
